### PR TITLE
:zap: add version.mk and UTs for some functions

### PR DESCRIPTION
**Pull request by haitwang-cloud**
- Added a version.mk file to maintain version information.
- Improved test coverage by adding unit tests for various functions.
- Enhanced the clarity and usefulness of the log messages.
- Optimized the UT function via GPT-4

### CODE REVIEW

**Comment by haitwang-cloud** [comment]
E2E testing results

### CUDA Sample ADD
图片
###

```
I0126 07:25:35.423645       1 scheduler.go:56] New Scheduler
I0126 07:25:35.424352       1 reflector.go:289] Starting reflector *v1.Node (1h0m0s) from pkg/mod/k8s.io/client-go@v0.28.3/tools/cache/reflector.go:229
I0126 07:25:35.424396       1 reflector.go:325] Listing and watching *v1.Node from pkg/mod/k8s.io/client-go@v0.28.3/tools/cache/reflector.go:229
I0126 07:25:35.424363       1 reflector.go:289] Starting reflector *v1.Pod (1h0m0s) from pkg/mod/k8s.io/client-go@v0.28.3/tools/cache/reflector.go:229
I0126 07:25:35.424558       1 reflector.go:325] Listing and watching *v1.Pod from pkg/mod/k8s.io/client-go@v0.28.3/tools/cache/reflector.go:229
I0126 07:25:35.524470       1 shared_informer.go:341] caches populated
I0126 07:25:37.866014       1 util.go:137] Start to decode container device GPU-3a6ec8f0-24eb-1905-1f17-7bdb4e850ffa,NVIDIA,16384,0:
I0126 07:25:37.866051       1 util.go:156] Finished decoding container devices. Total devices: 1
I0126 07:25:37.866062       1 pods.go:50] prepare to add pod tf-notebook-784bc4cc48-tkdtx in namespace gpu-test-workloads under node shoot--ait--datalake-nonprod-c32m384-v100g3-z1-67ff4-c88hd
I0126 07:25:37.866071       1 pods.go:54] Pod added: Name: tf-notebook-784bc4cc48-tkdtx, Uid: fb019b97-aaa1-42d5-a2c6-7b4e8d78724e, Namespace: gpu-test-workloads, NodeID: shoot--ait--datalake-nonprod-c32m384-v100g3-z1-67ff4-c88hd
I0126 07:25:37.867258       1 util.go:137] Start to decode container device GPU-1994560a-3835-34a1-9f93-634379429aa7,NVIDIA,16384,0:
I0126 07:25:37.867298       1 util.go:156] Finished decoding container devices. Total devices: 1
I0126 07:25:37.867323       1 pods.go:50] prepare to add pod cuda-sample-vector-add-6bcc768b8b-wsb9h in namespace gpu-test-workloads under node shoot--ait--datalake-nonprod-c32m384-v100g3-z1-67ff4-c88hd
I0126 07:25:37.867329       1 pods.go:54] Pod added: Name: cuda-sample-vector-add-6bcc768b8b-wsb9h, Uid: 1c7c1141-b1c3-43bb-87e6-52f139f62dec, Namespace: gpu-test-workloads, NodeID: shoot--ait--datalake-nonprod-c32m384-v100g3-z1-67ff4-c88hd
I0126 07:25:37.880609       1 util.go:137] Start to decode container device GPU-1994560a-3835-34a1-9f93-634379429aa7,NVIDIA,16384,0:
I0126 07:25:37.880628       1 util.go:156] Finished decoding container devices. Total devices: 1
I0126 07:25:37.880638       1 pods.go:50] prepare to add pod cuda-sample-vector-add-6bcc768b8b-wsb9h in namespace gpu-test-workloads under node shoot--ait--datalake-nonprod-c32m384-v100g3-z1-67ff4-c88hd
I0126 07:25:37.887119       1 util.go:137] Start to decode container device GPU-1994560a-3835-34a1-9f93-634379429aa7,NVIDIA,16384,0:
I0126 07:25:37.887150       1 util.go:156] Finished decoding container devices. Total devices: 1
I0126 07:25:37.887159       1 pods.go:50] prepare to add pod cuda-sample-vector-add-6bcc768b8b-wsb9h in namespace gpu-test-workloads under node shoot--ait--datalake-nonprod-c32m384-v100g3-z1-67ff4-c88hd
I0126 07:25:37.925756       1 shared_informer.go:341] caches populated
I0126 07:25:37.925833       1 route.go:42] Into Predicate Route outer func
I0126 07:25:37.929776       1 util.go:106] Encoded node Devices: GPU-1994560a-3835-34a1-9f93-634379429aa7,10,16384,100,NVIDIA-Tesla V100-PCIE-16GB,0,true:GPU-3a6ec8f0-24eb-1905-1f17-7bdb4e850ffa,10,16384,100,NVIDIA-Tesla V100-PCIE-16GB,0,true:GPU-be8f1dd7-5aac-73b5-b3d4-9e00a49b97b5,10,16384,100,NVIDIA-Tesla V100-PCIE-16GB,0,true:
I0126 07:25:37.929885       1 metrics.go:227] Initializing metrics for scheduler
```

**Comment by haitwang-cloud** [comment]
UT test results under dir /pkg/device-plugin/nvidiadevice/nvinternal/
```
go test ./pkg/device-plugin/nvidiadevice/nvinternal/... -v -count=1
?       4pd.io/k8s-vgpu/pkg/device-plugin/nvidiadevice/nvinternal/cdi   [no test files]
?       4pd.io/k8s-vgpu/pkg/device-plugin/nvidiadevice/nvinternal/info  [no test files]
?       4pd.io/k8s-vgpu/pkg/device-plugin/nvidiadevice/nvinternal/mig   [no test files]
?       4pd.io/k8s-vgpu/pkg/device-plugin/nvidiadevice/nvinternal/plugin/manager        [no test files]
I0126 09:22:39.476569   33479 client.go:33] InClusterConfig failed unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
E0126 09:22:39.476652   33479 client.go:36] BuildFromFlags failed stat /sapmnt/home/I742968/.kube/config: no such file or directory
=== RUN   Test_parseNvidiaNumaInfo
=== RUN   Test_parseNvidiaNumaInfo/single_Tesla_P4_NUMA
=== RUN   Test_parseNvidiaNumaInfo/two_Tesla_P4_NUMA_topo_with_index_0
=== RUN   Test_parseNvidiaNumaInfo/two_Tesla_P4_NUMA_topo_with_index_1
--- PASS: Test_parseNvidiaNumaInfo (0.00s)
    --- PASS: Test_parseNvidiaNumaInfo/single_Tesla_P4_NUMA (0.00s)
    --- PASS: Test_parseNvidiaNumaInfo/two_Tesla_P4_NUMA_topo_with_index_0 (0.00s)
    --- PASS: Test_parseNvidiaNumaInfo/two_Tesla_P4_NUMA_topo_with_index_1 (0.00s)
=== RUN   TestCDIAllocateResponse
=== RUN   TestCDIAllocateResponse/empty_device_list_has_empty_response
=== RUN   TestCDIAllocateResponse/CDI_disabled_has_empty_response
=== RUN   TestCDIAllocateResponse/single_device_is_added_to_annotations
=== RUN   TestCDIAllocateResponse/single_device_is_added_to_annotations_with_custom_prefix
=== RUN   TestCDIAllocateResponse/multiple_devices_are_added_to_annotations
=== RUN   TestCDIAllocateResponse/multiple_devices_are_added_to_annotations_with_custom_prefix
=== RUN   TestCDIAllocateResponse/mofed_devices_are_selected_if_configured
=== RUN   TestCDIAllocateResponse/gds_devices_are_selected_if_configured
=== RUN   TestCDIAllocateResponse/gds_and_mofed_devices_are_included_with_device_ids
--- PASS: TestCDIAllocateResponse (0.00s)
    --- PASS: TestCDIAllocateResponse/empty_device_list_has_empty_response (0.00s)
    --- PASS: TestCDIAllocateResponse/CDI_disabled_has_empty_response (0.00s)
    --- PASS: TestCDIAllocateResponse/single_device_is_added_to_annotations (0.00s)
    --- PASS: TestCDIAllocateResponse/single_device_is_added_to_annotations_with_custom_prefix (0.00s)
    --- PASS: TestCDIAllocateResponse/multiple_devices_are_added_to_annotations (0.00s)
    --- PASS: TestCDIAllocateResponse/multiple_devices_are_added_to_annotations_with_custom_prefix (0.00s)
    --- PASS: TestCDIAllocateResponse/mofed_devices_are_selected_if_configured (0.00s)
    --- PASS: TestCDIAllocateResponse/gds_devices_are_selected_if_configured (0.00s)
    --- PASS: TestCDIAllocateResponse/gds_and_mofed_devices_are_included_with_device_ids (0.00s)
=== RUN   Test_pathGeneration
--- PASS: Test_pathGeneration (0.00s)
PASS
ok      4pd.io/k8s-vgpu/pkg/device-plugin/nvidiadevice/nvinternal/plugin        0.020s
I0126 09:22:39.488353   33485 client.go:33] InClusterConfig failed unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
E0126 09:22:39.488520   33485 client.go:36] BuildFromFlags failed stat /sapmnt/home/I742968/.kube/config: no such file or directory
=== RUN   TestDeviceMapInsert
=== RUN   TestDeviceMapInsert/insert_into_empty_map
=== RUN   TestDeviceMapInsert/add_to_existing_resource
=== RUN   TestDeviceMapInsert/add_new_resource
=== RUN   TestDeviceMapInsert/overwrite_existing_device
--- PASS: TestDeviceMapInsert (0.00s)
    --- PASS: TestDeviceMapInsert/insert_into_empty_map (0.00s)
    --- PASS: TestDeviceMapInsert/add_to_existing_resource (0.00s)
    --- PASS: TestDeviceMapInsert/add_new_resource (0.00s)
    --- PASS: TestDeviceMapInsert/overwrite_existing_device (0.00s)
=== RUN   TestGetAdditionalXids
=== RUN   TestGetAdditionalXids/Empty_input
=== RUN   TestGetAdditionalXids/Only_comma
=== RUN   TestGetAdditionalXids/Non-integer_input
I0126 09:22:39.490411   33485 health.go:207] Ignoring malformed Xid value not-an-int: strconv.ParseUint: parsing "not-an-int": invalid syntax
=== RUN   TestGetAdditionalXids/Single_integer
=== RUN   TestGetAdditionalXids/Negative_integer
I0126 09:22:39.490881   33485 health.go:207] Ignoring malformed Xid value -68: strconv.ParseUint: parsing "-68": invalid syntax
=== RUN   TestGetAdditionalXids/Single_integer_with_trailing_spaces
=== RUN   TestGetAdditionalXids/Single_integer_followed_by_comma_without_trailing_number
=== RUN   TestGetAdditionalXids/Comma_without_preceding_number_followed_by_single_integer
=== RUN   TestGetAdditionalXids/Two_comma-separated_integers
=== RUN   TestGetAdditionalXids/Two_integers_separated_by_non-integer
I0126 09:22:39.491630   33485 health.go:207] Ignoring malformed Xid value not-an-int: strconv.ParseUint: parsing "not-an-int": invalid syntax
--- PASS: TestGetAdditionalXids (0.00s)
    --- PASS: TestGetAdditionalXids/Empty_input (0.00s)
    --- PASS: TestGetAdditionalXids/Only_comma (0.00s)
    --- PASS: TestGetAdditionalXids/Non-integer_input (0.00s)
    --- PASS: TestGetAdditionalXids/Single_integer (0.00s)
    --- PASS: TestGetAdditionalXids/Negative_integer (0.00s)
    --- PASS: TestGetAdditionalXids/Single_integer_with_trailing_spaces (0.00s)
    --- PASS: TestGetAdditionalXids/Single_integer_followed_by_comma_without_trailing_number (0.00s)
    --- PASS: TestGetAdditionalXids/Comma_without_preceding_number_followed_by_single_integer (0.00s)
    --- PASS: TestGetAdditionalXids/Two_comma-separated_integers (0.00s)
    --- PASS: TestGetAdditionalXids/Two_integers_separated_by_non-integer (0.00s)
PASS
ok      4pd.io/k8s-vgpu/pkg/device-plugin/nvidiadevice/nvinternal/rm    0.026s
```

**Comment by haitwang-cloud** [comment]
@archlitchi PTAL, tks

**Comment by haitwang-cloud** [comment]
@archlitchi Could u PTAL on this PR?

**Comment by archlitchi** [comment]
Thanks for contributing:)

**Pull request merged**
